version: "3.3"

services:
  photoview:
    image: viktorstrate/photoview:latest
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - mariadbforphotoview
    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:photosecret@tcp(mariadbforphotoview)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      
      # Optional: If you are using Samba/CIFS-Share and experience problems with "directory not found"
      # Enable the following Godebug
      # - GODEBUG=asyncpreemptoff=1
      
      
      # Optional: To enable map related features, you need to create a mapbox token.
      # A token can be generated for free here https://account.mapbox.com/access-tokens/
      # It's a good idea to limit the scope of the token to your own domain, to prevent others from using it.
      # - MAPBOX_TOKEN=<YOUR TOKEN HERE>

    volumes:
      - /media/photos/docker/storage/photoview/api_cache:/app/cache
      - /media/photos/WIP:/photos:ro
  mariadbforphotoview:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_DATABASE: "photoview"
      MYSQL_USER: "photoview"
      MYSQL_PASSWORD: "photosecret"
      MYSQL_RANDOM_ROOT_PASSWORD: "R00tN33dToChng3Ths"
    volumes:
      - /media/photos/docker/db/databasephotoview:/var/lib/mysql # DO NOT REMOVE