version: "3.3"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 8053:80/tcp
      - 8443:443/tcp
    networks:
      default:
        ipv4_address: 172.20.4.20
    volumes:
      - ${CONTAINERS}/adguard/workdir:/opt/adguardhome/work
      - ${CONTAINERS}/adguard:/opt/adguardhome/conf
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.rule=Host(`adguard.${DOMAIN}`)
      - traefik.http.services.adguard.loadbalancer.server.port=80
      - traefik.http.routers.adguard.entrypoints=websecured
      - traefik.http.routers.adguard.tls.certresolver=myresolver
    restart: unless-stopped